### PR TITLE
Fix links in the readme

### PR DESCRIPTION
**Pull request by aaltay**
Fixes https://github.com/GoogleCloudPlatform/DataflowJavaSDK-examples/issues/10

### CODE REVIEW

**Comment by dhalperi** [comment]
This seems like the wrong fix -- @davorbonaci why did you suggest this?

Either we update DataflowJavaSDK-examples for v2.0.0, we delete it, or we make it point to the `master-1.x` branch instead of `master`. None of these is great (I'd suggest deleting the repo most of all, as it never brought us anything good).

**Comment by aaltay** [comment]
We can also re-purpose it as an example store for all dataflow 2.0 SDKs with original content, that does not point to other repos.

**Comment by davorbonaci** [comment]
I don't remember suggesting anything ;-)

We shouldn't be pointing to other repositories; all links should point to this repository, and preferably be relative, not absolute.

**Comment by aaltay** [comment]
Updated links to be relative. Verified all links on both readme files.

**Comment by miketruty** [comment]
Shouldn't we fix https://github.com/GoogleCloudPlatform/DataflowSDK-examples (master README.md) since that's what appears to new users?

**Comment by davorbonaci** [comment]
(we should; it should happen shortly.)

**Pull request merged**
